# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-eval
        entry: 'nocheckin'
        language: pygrep
        files: ^(?!.pre-commit-config).*.(h|c|hpp|cpp|json|jsonc|yaml|yml|txt|py|md|toml|cfg)$
        types: []
  - repo: local
    hooks:
      - id: cog-readme
        name: cog-readme
        entry: uv run cog -n utf-8 -U -r -P --markers="[[[cog cog]]] [[[end]]]" README.md
        stages: [pre-commit, pre-merge-commit, manual]
        require_serial: true
        pass_filenames: false
        always_run: true
        language: system
